### ISSUE TITLE
我用七牛上传文件，但我想在token中传url，貌似不行

### ISSUE THREAD

**Issue by boiawang** [mycolorway/simditor#223]
```
params: {
  token: "/token"
}
```

这样返回401

**Comment by farthinker** [comment]
@boiawang 我不知道你的问题出在哪里，我们使用七牛的时候也是这样传token的：
```
        url: zhiren.qiniu.uploadPath
        fileKey: 'file'
        params:
          token: zhiren.qiniu.uptoken.attachment
          'x:category': category
```
