### ISSUE TITLE
使用七牛上传返回file is not specified in multipart

### ISSUE THREAD

**Issue by wtwei** [mycolorway/simditor#321]
上传图片到七牛，七牛返回file is not specified in multipart的错误是什么原因啊

**Comment by farthinker** [comment]
http://segmentfault.com/q/1010000000326830

初始化simditor的时候设置fileKey（相关文档：http://simditor.tower.im/docs/doc-config.html#anchor-upload）：
```
editor = new Simditor
  textarea: $('#editor')
  upload:
    url: 'xxx'
    fileKey: 'file'
```
